spring:
  datasource:
    url: jdbc:mysql://ximollacer_mysql:3306/book_archive
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true
    user: root
    password: root
    url: jdbc:mysql://ximollacer_mysql:3306/book_archive
    locations: classpath:/db
    baseline-version: 0
    baseline-on-migrate: true
