spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_archive
    username: root
    password: 1q2w3e
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true
    user: root
    password: 1q2w3e
    url: jdbc:mysql://localhost:3306/book_archive
    locations: classpath:/db
    baseline-version: 0
    baseline-on-migrate: true
