spring:
  datasource:
    url: jdbc:mysql://bookarchive_db:3306/book_archive
    username: book_archive
    password: book_archive
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    show-sql: true

  flyway:
    enabled: true
    user: book_archive
    password: book_archive
    url: jdbc:mysql://bookarchive_db:3306/book_archive
    locations: classpath:/db
    baseline-version: 0
    baseline-on-migrate: true
